// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV-sK8snFgJ9_gi0d7oRUf3-KR-RP15Ww',
    appId: '1:867087321654:web:fdd790ec18295e39dd2697',
    messagingSenderId: '867087321654',
    projectId: 'mindcare-b1b98',
    authDomain: 'mindcare-b1b98.firebaseapp.com',
    storageBucket: 'mindcare-b1b98.firebasestorage.app',
    measurementId: 'G-XDNQBRX4H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMHhl0NTNGO_45TSoEeaBexXkP7oUti8',
    appId: '1:867087321654:android:31b0be116851def1dd2697',
    messagingSenderId: '867087321654',
    projectId: 'mindcare-b1b98',
    storageBucket: 'mindcare-b1b98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKjSq8lJ23nhmR-fqPZxRzCgWIV4_xI64',
    appId: '1:867087321654:ios:b26bfbc828fdc0a8dd2697',
    messagingSenderId: '867087321654',
    projectId: 'mindcare-b1b98',
    storageBucket: 'mindcare-b1b98.firebasestorage.app',
    iosBundleId: 'com.example.capstone6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKjSq8lJ23nhmR-fqPZxRzCgWIV4_xI64',
    appId: '1:867087321654:ios:b26bfbc828fdc0a8dd2697',
    messagingSenderId: '867087321654',
    projectId: 'mindcare-b1b98',
    storageBucket: 'mindcare-b1b98.firebasestorage.app',
    iosBundleId: 'com.example.capstone6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV-sK8snFgJ9_gi0d7oRUf3-KR-RP15Ww',
    appId: '1:867087321654:web:9aae0e6315a82da4dd2697',
    messagingSenderId: '867087321654',
    projectId: 'mindcare-b1b98',
    authDomain: 'mindcare-b1b98.firebaseapp.com',
    storageBucket: 'mindcare-b1b98.firebasestorage.app',
    measurementId: 'G-E9N147V2LP',
  );
}
